In [79]:
#from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pickle
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
## Load the data set
import pandas as pd

ssX = pickle.load(open('ssX.pkl','rb'))
df = pd.read_pickle('sampled_data_bands.pkl')
pipeline = pickle.load(open('model_new.pkl','rb'))
testing_data = pickle.load(open('test_data.pkl','rb'))
#test_data_unscaled = pd.read_pickle('test_data_unscaled.pkl')
#features = {'tempo': 86.1328125, 'mean_harmonic_ratio': 1.4627255, 'mean_spectral_centroid': 3189.5947603195004, 'mean_spectral_flatness': 0.075906955, 'count_delta_above_mean': 0, 'ratio_above_rmse_mean': 0.9502262443438914, 'max_rmse': 0.31629544, 'mean_rmse': 0.21298172, 'mean_zcr': 0.17211970707656613}
#features = {'tempo': 123.046875, 'mean_harmonic_ratio': 12.582852, 'mean_spectral_centroid': 721.8471383960348, 'mean_spectral_flatness': 0.000115590585, 'count_delta_above_mean': 0, 'ratio_above_rmse_mean': 1.2046511627906977, 'max_rmse': 0.2067693, 'mean_rmse': 0.12706026, 'mean_zcr': 0.0265557011471519}

features

{'tempo': 123.046875,
 'mean_harmonic_ratio': 12.582852,
 'mean_spectral_centroid': 721.8471383960348,
 'mean_spectral_flatness': 0.000115590585,
 'count_delta_above_mean': 0,
 'ratio_above_rmse_mean': 1.2046511627906977,
 'max_rmse': 0.2067693,
 'mean_rmse': 0.12706026,
 'mean_zcr': 0.0265557011471519}

In [67]:
X = np.asarray([features['tempo'], features['mean_harmonic_ratio'], features['mean_spectral_centroid'],
                  features['mean_spectral_flatness'], features['count_delta_above_mean'], features['ratio_above_rmse_mean'],
                  features['max_rmse'], features['mean_rmse'], features['mean_zcr']], dtype=np.float64).reshape(1,-1)
Xscaled= ssX.transform(X)
prob_metallica = pipeline.predict_proba(Xscaled)[0,1]
prob_metallica

0.22238209303453516

In [62]:
X,testing_data[0][4,:]

(array([[8.61328125e+01, 1.46272550e+00, 3.18959476e+03, 7.59069550e-02,
         0.00000000e+00, 9.50226244e-01, 3.16295440e-01, 2.12981720e-01,
         1.72119707e-01]]),
 array([ 0.33327466, -0.18463995, -1.17126828, -1.0251325 ,  1.08957766,
        -1.91151582, -1.05712077, -1.16203126, -0.94248979]))

In [78]:
prob_metallica = pipeline.predict_proba(testing_data[0])[1,1]
prob_metallica

0.7549389042363569

In [4]:
df.loc[test_data_unscaled.index.values,:]
#test_data_unscaled.iloc[7,:]
#df
#predictions_model1 = pipeline_1.predict_proba(example)
#features

index                                 track_name                 bpm  \
1766    2207                     10 - Metal Militia.mp3          172.265625   
7978    2572                        3 - Ghost Rider.mp3        129.19921875   
4184    3662                     3 - Half The World.mp3           95.703125   
2109     481                      06 - Killing Time.mp3  112.34714673913044   
3181    1242                              5 - Scars.mp3        129.19921875   
3422    2481                    01 - Hit The Lights.mp3      161.4990234375   
6006    1135               11 - My Friend Of Misery.mp3  117.45383522727273   
1786     402                          5 - Spindrift.mp3  112.34714673913044   
33      5840                    08 - Justice Medley.mp3   89.10290948275862   
6281    3047                     04 - Fade To Black.mp3  112.34714673913044   
5403    3928                07 - The Unforgiven III.mp3        129.19921875   
9557    1815                 07 - Through The Never.mp3           95.703125   
7207    2623                      05 - King Nothing.mp3  112.34714673913044   
10699   2323  08 - Live At Wembley Stadium London 3.mp3         143.5546875   
1501    1466            4 - By-Tor And The Snow Dog.mp3       107.666015625   
3418    2564                                Sound 2.mp3   78.30255681818181   
3194    3531                       5 - Fly By Night.mp3         92.28515625   
8510    2821                        10 - High Water.mp3          123.046875   
2453    5148                    01 - Ain't My Bitch.mp3      161.4990234375   
9166    1383                     06 - Leper Messiah.mp3         143.5546875   
4228    5560               03 - Eye Of The Beholder.mp3          123.046875   
9854    6161                      04 - Dirty Window.mp3   63.02400914634146   
6173    1941                           3 - The Pass.mp3  117.45383522727273   
9650    6273               02 - Wherever I May Roam.mp3         143.5546875   
7303    3309                         1 - Tom Sawyer.mp3          86.1328125   
10677   2763                 10 - You Bet Your Life.mp3        129.19921875   
9254    4723                             02 - 2 X 4.mp3  117.45383522727273   
5120    2569                                Sound 2.mp3  151.99908088235293   
6724    3745                3 - For What It's Worth.mp3  198.76802884615384   
8976    2767                 10 - You Bet Your Life.mp3        129.19921875   
...      ...                                        ...                 ...   
8514     708                     2 - Need Some Love.mp3         143.5546875   
3781    3900               14 - Sad But True (Live).mp3         92.28515625   
7767    4331                           06 - Cyanide.mp3  135.99917763157896   
9447    3463                             2 - Xanadu.mp3         92.28515625   
247     1496                 8 - Between The Wheels.mp3         143.5546875   
5127     199              16 - Whereever I May Roam.mp3  135.99917763157896   
2900    2208                4 - La Villa Strangiato.mp3  151.99908088235293   
1982    1582                        07 - Blitzkrieg.mp3   99.38401442307692   
6879     608                               8 - Hope.mp3   83.35433467741936   
6329    2599          01 - Free Speech For The Dumb.mp3   99.38401442307692   
199     3790                         2 - Afterimage.mp3  151.99908088235293   
8568    1998                         10 - Am I Evil.mp3         184.5703125   
485     3288                   06 - The Small Hours.mp3         184.5703125   
2879    3622                       7 - Vapor Trails.mp3  112.34714673913044   
9647    5289          05 - Last Caress - Green Hell.mp3   99.38401442307692   
5066    4144                    07 - The Unforgiven.mp3         71.77734375   
2823     525                   1 - Summertime Blues.mp3          86.1328125   
455     3386                   4 - The Enemy Within.mp3         71.77734375   
10618   1127             2 - I Think I'm Going Bald.mp3  

In [160]:
test_data_unscaled.iloc[7,:]

bpm                        112.347147
harmonic_rythmic_ratio       3.060284
spectral_centroid         2339.582611
spectral_flatness            0.026535
count_delta_above_mean       0.000000
ratio_above_rmse_mean        0.664093
max_rmse                     0.350063
mean_rms                     0.240684
mean_zcr                     0.132440
Name: 1786, dtype: float64

In [ ]:
features = {'tempo': 117.45383522727273, 
            'mean_harmonic_ratio': 1.992991, 
            'mean_spectral_centroid': 3235.5694860332565, 
            'mean_spectral_flatness': 0.06502251, 
            'count_delta_above_mean': 1, 
            'count_rmse_above_mean': 1.066420664206642, 
            'max_rmse': 0.254529, 
            'mean_rmse': 0.13620129, 
            'mean_zcr': 0.16601126534598215}

In [3]:
predictions_model1[:10]

array([[0.99450441, 0.00549559],
       [0.61250459, 0.38749541],
       [0.19923142, 0.80076858],
       [0.86092306, 0.13907694],
       [0.03384911, 0.96615089],
       [0.97561695, 0.02438305],
       [0.93584553, 0.06415447],
       [0.14291402, 0.85708598],
       [0.85743026, 0.14256974],
       [0.48494428, 0.51505572]])

In [21]:
pipeline_3 = pickle.load(open('model3.pkl','rb'))
testing_data3 = pickle.load(open('test_data3.pkl','rb'))


ValueError: non-broadcastable output operand with shape (32510,1) doesn't match the broadcast shape (32510,84)

In [ ]:
predictions_model3 = pipeline_3.predict_proba(testing_data3[0].reshape(-1,1))

In [12]:
df = pd.read_pickle('sampled_data_bands.pkl')

In [13]:
df.head()

index                     track_name                bpm  \
0    148              4 - Limelight.mp3  89.10290948275862   
1   3722  07 - Orion (Instrumental).mp3       129.19921875   
2   2120           1 - Bastille Day.mp3         103.359375   
3   2441             02 - St. Anger.mp3        92.28515625   
4   3197              08 - The Wait.mp3     161.4990234375   

  harmonic_rythmic_ratio   spectral_centroid spectral_flatness  \
0              3.5583296  1686.4585213145274        0.00582094   
1              4.8556867  2000.2844087632832       0.013070458   
2              1.3164884  2098.2022756528363       0.019427974   
3              1.5321984  2545.9767516650304       0.038557682   
4              3.1249948  1838.5850343973295       0.013156818   

  count_delta_above_mean ratio_above_rmse_mean     max_rmse     mean_rms  \
0                      0    0.6911764705882353  0.097900845  0.056995194   
1                     12    0.5436241610738255   0.20186672  0.079553574   
2                      0    1.2958579881656804   0.27656603    0.1475775   
3                      0     1.169064748201439   0.42648128   0.33256802   
4                      0    0.9695431472081218   0.15927805  0.119250305   

              mean_zcr       band  
0  0.07279778079710145       Rush  
1  0.06671832540760869  Metallica  
2  0.10958767920425258       Rush  
3  0.14184691775497513  Metallica  
4  0.06252768605025773  Metallica

In [14]:
df.loc[1,:]

index                                              3722
track_name                07 - Orion (Instrumental).mp3
bpm                                        129.19921875
harmonic_rythmic_ratio                        4.8556867
spectral_centroid                    2000.2844087632832
spectral_flatness                           0.013070458
count_delta_above_mean                               12
ratio_above_rmse_mean                0.5436241610738255
max_rmse                                     0.20186672
mean_rms                                    0.079553574
mean_zcr                            0.06671832540760869
band                                          Metallica
Name: 1, dtype: object